export { PACKAGE, getPublicSupabaseEnv, getServiceSupabaseEnv, isDbTestConfigured, isSupabaseConfigured } from './env';
export {
  createBrowserSupabase,
  createCookieSupabase,
  type CookieMethodsServer,
} from './client';
export type {
  AgentRun,
  Database,
  Food,
  FoodEntry,
  FoodEntryInsert,
  FoodInsert,
  MealTemplate,
  Profile,
  Recipe,
  Serving,
  ServingInsert,
  WeightLog,
  Workout,
  WorkoutSet,
} from './database';
export {
  DbQueryError,
  isMissingRpcError,
  isUnauthorizedError,
  isUniqueViolation,
  clampUpdatedAt,
  clampUpdatedAtIso,
  getFood,
  getFoodBySource,
  getFoodsByBarcode,
  getFoodsByIds,
  getFoodLogCounts,
  getProfile,
  incomingWins,
  insertCanonicalFood,
  insertFoodAliases,
  insertFoodEntry,
  insertServings,
  insertUserFood,
  listFoodAliases,
  listFoodsBySource,
  insertWeightLog,
  insertWorkout,
  listAgentRuns,
  listFoodEntriesByLogicalDate,
  listFoodEntriesSince,
  listMealTemplates,
  listServings,
  listServingsByFoodIds,
  listVisibleFoods,
  listWeightLogsByLogicalDate,
  listWorkoutSets,
  listWorkoutsByLogicalDate,
  markAgentRunScrubbed,
  omitServerCursor,
  queueOffContribute,
  searchFoods,
  tombstoneFoodEntry,
  tombstoneMealTemplate,
  tombstoneUserFood,
  tombstoneWeightLog,
  tombstoneWorkout,
  tombstoneWorkoutSet,
  updateProfile,
  upsertFoodEntry,
  upsertMealTemplate,
} from './queries';
export type { FoodSearchHit } from './queries';
export { mealTemplateItemSchema } from './queries';
export type { MealTemplateItem } from './schema';
export type { PhCoreFoodRow } from './ph-core-types';
export type { DbClient, FoodEntryWrite, MealTemplateWrite, UpsertMealTemplateResult, UpsertResult } from './queries';
