export const PACKAGE = '@kayamo/offline';

export { backoffMs } from './backoff';
export { getOfflineDb, resetOfflineDb, type KayaMoDB } from './db';
export type {
  LocalAgentMemory,
  LocalAchievementDefinition,
  LocalCocoConversation,
  LocalCocoMessage,
  LocalDailyLoopPreference,
  LocalDailyPlan,
  LocalCompanionEvent,
  LocalCompanionState,
  LocalCosmeticDefinition,
  LocalCosmeticUnlock,
  LocalFood,
  LocalExercise,
  LocalFoodEntry,
  LocalFocusSession,
  LocalEvolutionStage,
  LocalCompass,
  LocalFutureSelf,
  LocalGoal,
  LocalGoalMilestone,
  LocalInboxItem,
  LocalGuidanceSnapshot,
  LocalHabit,
  LocalHabitCompletion,
  LocalMealTemplate,
  LocalPersonalRule,
  LocalJournalEntry,
  LocalBusyBlock,
  LocalActionGrants,
  LocalLifeStoryEntry,
  LocalGroveChapter,
  LocalRoutine,
  LocalRoutineCompletion,
  LocalServing,
  LocalScripturePassage,
  LocalTask,
  LocalUserAchievement,
  LocalWeightLog,
  LocalWorkout,
  LocalWorkoutPlan,
  LocalWorkoutPlanExercise,
  LocalWorkoutSet,
  LocalRestTimer,
  SyncQueueItem,
  SyncableTable,
} from './db';
export {
  cacheGuidanceSnapshot,
  clearCachedGuidanceSnapshot,
  getCachedGuidanceSnapshot,
} from './guidance';
export {
  completeLocalEveningReflection,
  createLocalFocusSession,
  ensureReviewedScriptureCache,
  finishLocalFocusSession,
  getLocalDailyLoopPreferences,
  getLocalDailyPlan,
  listLocalDailyPlans,
  listLocalFocusHistory,
  listLocalFocusSessions,
  listLocalScripture,
  mergeRemoteDailyPlans,
  mergeRemoteFocusSessions,
  saveLocalDailyLoopPreferences,
  saveLocalDailyPlan,
  startLocalFocusSession,
  tombstoneLocalDailyPlan,
  tombstoneLocalFocusSession,
} from './daily-loop';
export {
  appendLocalCocoMessage,
  createLocalAgentMemory,
  createLocalCocoConversation,
  deleteLocalJournalEntry,
  listLocalAgentMemories,
  listLocalCocoConversations,
  listLocalCocoMessages,
  listLocalJournalEntries,
  mergeRemoteAgentMemories,
  mergeRemoteCocoConversations,
  mergeRemoteCocoMessages,
  rememberJournalEntry,
  saveLocalJournalEntry,
  tombstoneLocalAgentMemory,
  tombstoneLocalCocoConversation,
  tombstoneLocalCocoMessage,
} from './coco';
export {
  createLocalBusyBlock,
  getLocalActionGrants,
  listLocalBusyBlocks,
  saveLocalActionGrant,
  tombstoneLocalBusyBlock,
} from './integrations';
export {
  closeLocalGroveChapter,
  createLocalLifeStoryEntry,
  listLocalGroveChapters,
  listLocalLifeStory,
  tombstoneLocalLifeStoryEntry,
} from './archive';
export {
  completeLocalRoutine,
  createLocalRoutine,
  createLocalTask,
  listLocalRoutineCompletions,
  listLocalRoutines,
  listLocalOpenTasks,
  listLocalTasks,
  listLocalTasksForDate,
  mergeRemoteRoutineCompletions,
  mergeRemoteRoutines,
  mergeRemoteTasks,
  setLocalTaskCompleted,
  setLocalTaskScheduledFor,
  tombstoneLocalRoutine,
  tombstoneLocalRoutineCompletion,
  tombstoneLocalTask,
} from './planning';
export {
  completeLocalGoalMilestone,
  completeLocalHabit,
  createLocalCompanionEvent,
  createLocalGoal,
  createLocalGoalMilestone,
  createLocalHabit,
  getLocalCompanionProgression,
  listLocalCompanionEvents,
  listLocalCompanionPresenceDates,
  listLocalGoalMilestones,
  listLocalGoals,
  listLocalHabitCompletions,
  listLocalHabits,
  mergeRemoteCompanionEvents,
  mergeRemoteGoalMilestones,
  mergeRemoteGoals,
  mergeRemoteHabitCompletions,
  mergeRemoteHabits,
  setLocalGoalStatus,
  tombstoneLocalGoal,
  updateLocalGoalMilestone,
} from './journey';
export {
  createLocalInboxItem,
  createLocalPersonalRule,
  getLocalCompass,
  getLocalFutureSelf,
  listLocalInboxItems,
  listLocalPersonalRules,
  processLocalInboxItem,
  mergeRemoteCompasses,
  mergeRemoteFutureSelves,
  mergeRemoteInboxItems,
  mergeRemotePersonalRules,
  saveLocalCompass,
  saveLocalFutureSelf,
  tombstoneLocalInboxItem,
} from './identity';
export {
  cacheFood,
  cacheFoodWithServings,
  getCachedFood,
  getCachedServings,
  getFoodReadThrough,
  listCachedFoodsWithServings,
} from './foods-cache';
export {
  useLiveFoodEntries,
  useLiveFoodHistory,
  useLiveMealTemplates,
  useSyncStatus,
} from './hooks';
export { instantOnLogicalDate, localHourFromInstant, logicalDateFromInstant } from './logical-date';
export { enqueueUpsert, pendingCount } from './queue';
export { getSyncStatusSnapshot, startSync, type SyncDeps, type SyncStatus } from './sync';
export {
  listLocalFoodEntries,
  listLocalFoodHistory,
  listLocalMealTemplates,
  listLocalWeightLogs,
  logFoodEntries,
  logFoodEntry,
  logWeight,
  restoreLocalFoodEntry,
  reviseLocalFoodEntry,
  logWorkout,
  mergeRemoteFoodEntries,
  mergeRemoteMealTemplates,
  mergeRemoteWeightLogs,
  recomputeLocalLogicalDates,
  saveMealTemplate,
  tombstoneLocalFoodEntries,
  tombstoneLocalFoodEntry,
  tombstoneLocalMealTemplate,
  tombstoneLocalWeightLog,
  type LogFoodEntryInput,
} from './writes';
export {
  clearLocalRestTimer,
  completeLocalWorkoutSet,
  extendLocalRestTimer,
  finishLocalWorkout,
  getLocalRestTimer,
  listLocalWorkoutHistory,
  listLocalWorkoutSets,
  mergeRemoteExercises,
  mergeRemoteWorkoutPlanExercises,
  mergeRemoteWorkoutPlans,
  mergeRemoteWorkoutSets,
  mergeRemoteWorkouts,
  saveLocalWorkoutPlan,
  saveLocalWorkoutPlanExercise,
  startLocalRestTimer,
  startLocalWorkout,
  tombstoneLocalWorkout,
} from './training';
